LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := opsqlite

LOCAL_SRC_FILES := $(wildcard \
$(LOCAL_PATH)/opsqlite/*.cpp \
$(LOCAL_PATH)/opsqlite/*.c \
)

LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

# https://github.com/OP-Engineering/op-sqlite
SQLITE3_PERFORMANCE_FLAGS := -DSQLITE_DQS=0 -DSQLITE_THREADSAFE=0 -DSQLITE_DEFAULT_MEMSTATUS=0 -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS=1 -DSQLITE_MAX_EXPR_DEPTH=0 -DSQLITE_OMIT_DEPRECATED=1 -DSQLITE_OMIT_PROGRESS_CALLBACK=1 -DSQLITE_OMIT_SHARED_CACHE=1 -DSQLITE_USE_ALLOCA=1

LOCAL_CFLAGS := -fexceptions -frtti -O3 ${SQLITE3_PERFORMANCE_FLAGS}

LOCAL_STATIC_LIBRARIES := callinvoker
LOCAL_SHARED_LIBRARIES := libjsi

include $(BUILD_SHARED_LIBRARY)
